FROM ubuntu:22.04@sha256:1ec65b2719518e27d4d25f104d93f9fac60dc437f81452302406825c46fcc9cb

ENV DEBIAN_FRONTEND=noninteractive

ARG VERSION=main
ARG REPO=https://github.com/MrDave/StaticJinjaPlus.git

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends git python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN git clone ${REPO} /StaticJinjaPlus

WORKDIR /StaticJinjaPlus

RUN if [ "$VERSION" != "main" ]; then git checkout $VERSION; fi

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "main.py", "--srcpath", "./templates"] 